[build]
  command = "yarn build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_SERVER_URL = "https://droptext-server.herokuapp.com/"
