[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3"
actix-cors = "0.5.4"
serde = "1.0.127"
serde_json = "1.0.66"
mongodb = "1.2.2"
nanoid = "0.4.0"
dotenv = "0.15.0"
